language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-progress

script: vendor/bin/phpunit
